version: "3.1"
services:
  eureka-server:
    image: williama1pha/cardinalis-be-eureka-server
    ports:
      - '9000:9000'
    restart: always
    networks:
      - twitter-network
  gateway:
    image: williama1pha/cardinalis-be-gateway
    ports:
      - '9002:9002'
    networks:
      - twitter-network
    environment:
      - EUREKA_URL=http://eureka-server:9000/eureka
    links:
      - "eureka-server"
    depends_on:
      - eureka-server
  user-service:
    image: williama1pha/cardinalis-be-user-service
    networks:
      - twitter-network
    ports:
      - '8081:8081'
    environment:
      - USER_DB=postgres
      - PASSWORD_DB=OYl4vnn9ULlV3Sc3tDNj
      - HOST_DB=jdbc:postgresql://containers-us-west-59.railway.app:6571/railway
      - EUREKA_URL=http://eureka-server:9000/eureka
    links:
      - "eureka-server"
    depends_on:
      - eureka-server
      - gateway
  tweet-service:
    image: williama1pha/cardinalis-be-tweet-service
    platform: linux/amd64
    networks:
      - twitter-network
    ports:
      - '8080:8080'
    environment:
      - USER_DB=postgres
      - PASSWORD_DB=V8GFrDT8372Cjw3uAY80
      - HOST_DB=jdbc:postgresql://containers-us-west-143.railway.app:7614/railway
      - EUREKA_URL=http://eureka-server:9000/eureka
    links:
      - "eureka-server"
    depends_on:
      - eureka-server
      - gateway
networks:
  twitter-network: