version: "3.1"
services:
  gateway:
    container_name: gateway
    build: ./gateway
    restart: always
    networks:
      - twitter-network
    ports:
      - '9002:9002'
    environment:
      - DOCKER_DEFAULT_PLATFORM=linux/amd64 docker-compose build

  user-service:
    container_name: user-service
    build: ./user-service
    networks:
      - twitter-network
    ports:
      - '8081:8081'
    environment:
      - USER_DB=postgres
      - PASSWORD_DB=OYl4vnn9ULlV3Sc3tDNj
      - HOST_DB=jdbc:postgresql://containers-us-west-59.railway.app:6571/railway
      - EUREKA_URL=http://eureka-server:9000/eureka
    depends_on:
      - gateway
  tweet-service:
    container_name: tweet-service
    build: ./tweet-service
    networks:
      - twitter-network
    ports:
      - '8080:8080'
    environment:
      - USER_DB=postgres
      - PASSWORD_DB=V8GFrDT8372Cjw3uAY80
      - HOST_DB=jdbc:postgresql://containers-us-west-143.railway.app:7614/railway
    depends_on:
      - gateway
networks:
  twitter-network: