xservices:
  tweet-service:
    container_name: tweet-service
    image: cardinalis/tweet-service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 131001
      PGDATA: /data/postgres
    volumes:
      - tweet-service:/data/postgres
    ports:
      - "3306:3306"
    networks:
      - postgres
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 131001
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped


volumes:
  tweet-service:
  postgres:
  pgadmin:

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge
