version: "3.1"
services:
  gateway:
    container_name: gateway
    build: ./gateway
    restart: always
    networks:
      - twitter-network
    ports:
      - '9002:9002'
  user-service:
    container_name: user-service
    build: ./user-service
    networks:
      - twitter-network
    ports:
      - '8081:8081'
    environment:
      - HOST_DB=jdbc:postgresql://database-user:5432/cardinalis
    depends_on:
      - gateway
  tweet-service:
    container_name: tweet-service
    build: ./tweet-service
    networks:
      - twitter-network
    ports:
      - '8080:8080'
    environment:
      - HOST_DB=jdbc:postgresql://database-tweet:5432/cardinalis
    depends_on:
      - gateway
networks:
  twitter-network: