apiVersion: skaffold/v3
kind: Config
metadata:
  name: cardinalis-be
build:
  artifacts:
  - image: us-central1-docker.pkg.dev/proven-solstice-371106/cardinalis/tweet-service
    context: tweet-service
    jib:
      project: com.cardinalis:tweet-service
  - image: us-central1-docker.pkg.dev/proven-solstice-371106/cardinalis/user-service
    context: user-service
    jib:
      project: com.cardinalis:user-service
manifests:
  rawYaml:
  - k8s/ingress.yaml
  - k8s/tweet-service.yaml
  - k8s/user-service.yaml
