server:
  port: 3001
spring:
  application:
    name: timeline-service

  redis:
#    host: ${REDIS_URL:redis://default:bKHo0mmnI1atx5ULubqR@containers-us-west-161.railway.app:6394}
    host: ${REDIS_URL:localhost}
    port: ${REDIS_PORT:6379}

jwt:
  secret: screte-value
  expiration: 86400000

