server:
  port: 9002
spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:5173"
            allowed-methods: "*"
            allowed-headers: "*"
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**,/auth/**
        - id: tweet-service
          uri: lb://tweet-service
          predicates:
            - Path=/tweet/**
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:9000/eureka}
    fetch-registry: true
    register-with-eureka: true