server:
  port: 3000
spring:
  application:
    name: gateway
  cloud:
    kubernetes:
      loadbalancer:
        mode: service
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allowed-origin-patterns:
              - "/**"
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<path>.*), /$\{path}
        - id: tweet-service
          uri: lb://tweet-service
          predicates:
            - Path=/tweet/**'
          filters:
            - RewritePath=/tweet/(?<path>.*), /$\{path}
        - id: tweet-service
          uri: lb://timeline-service
          predicates:
            - Path=/timeline/**'
          filters:
            - RewritePath=/timeline/(?<path>.*), /$\{path}

jwt:
  secret: dejavu

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info