server:
  port: 9002
spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**,/auth/**
        - id: tweet-service
          uri: lb://tweet-service
          predicates:
            - Path=/tweet/**
jwt:
  secret: screte-value

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info