server:
  port: 9002

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**,/auth/**
        - id: tweet-service
          uri: lb://tweet-service
          predicates:
            - Path=/api/tweet/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
    fetch-registry: true
    register-with-eureka: true